test optimize precise-output
set opt_level=speed
target x86_64

function %fold_xor_from_and_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bnot v1
    v3 = band v0, v2
    v4 = bnot v0
    v5 = band v4, v1
    v6 = bor v3, v5
    return v6
}

; function %fold_xor_from_and_not_i32(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v6 = bxor v0, v1
;     return v6
; }



function %fold_xor_from_and_not_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = bnot v1
    v3 = band v0, v2
    v4 = bnot v0
    v5 = band v4, v1
    v6 = bor v3, v5
    return v6
}

; function %fold_xor_from_and_not_i64(i64, i64) -> i64 fast {
; block0(v0: i64, v1: i64):
;     v6 = bxor v0, v1
;     return v6
; }


