test optimize precise-output
set opt_level=speed
target x86_64

function %fold_not_add_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = iadd v2, v1
    v4 = bnot v3
    return v4
}

; function %fold_not_add_not_i32(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = isub v0, v1
;     return v5
; }



function %fold_not_add_not_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = bnot v0
    v3 = iadd v2, v1
    v4 = bnot v3
    return v4
}

; function %fold_not_add_not_i64(i64, i64) -> i64 fast {
; block0(v0: i64, v1: i64):
;     v5 = isub v0, v1
;     return v5
; }


