test optimize precise-output
set opt_level=speed
target x86_64

function %fold_bxor_bor_sub_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bxor v0, v1
    v3 = bor v0, v1
    v4 = isub v2, v3
    return v4
}

; function %fold_bxor_bor_sub_i32(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = band v0, v1
;     v6 = isub iconst.i32 0, v5
;     return v6
; }



function %fold_bxor_bor_sub_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = bxor v0, v1
    v3 = bor v0, v1
    v4 = isub v2, v3
    return v4
}

; function %fold_bxor_bor_sub_i64(i64, i64) -> i64 fast {
; block0(v0: i64, v1: i64):
;     v5 = band v0, v1
;     v6 = isub iconst.i64 0, v5
;     return v6
; }


